services:
  - type: web_service
    name: titanic-backend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT

  - type: web_service
    name: titanic-frontend
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://titanic-backend.onrender.com
